### ISSUE TITLE
New navbar header construction

### ISSUE THREAD

**Issue by akelch11** [akelch11/MealMatch#22]
One requirement for the checklist is creating a navbar with links to important pages. For now, I have deemed these the homescreen, matches page, and the previous items in the navbar.

On header navbar on the **dev branch**, the elements "Homescreen Matches .. etc." need to be moved to the right side. Currently they are on the left with the MealMatch title and I can't get them to the right side where they would ideally be.

Additionally, on collapse when the page is resizes to a small window, the navbar should collapse into a hamburger icon with the same links/items. The navbar currently collapses on every page except the landing page, but does not reveal a hamburger icon button.

Any help would be appreciated, front end burning me out

Potenital help:
https://getbootstrap.com/docs/4.0/components/navbar/
https://getbootstrap.com/docs/4.1/utilities/flex/#order
https://stackoverflow.com/questions/41513463/bootstrap-align-navbar-items-to-the-right

**Comment by jdapaah** [comment]
W.
