### ISSUE TITLE
Grad Student Hack

### ISSUE THREAD

**Issue by jdapaah** [akelch11/MealMatch#23]
Right now Grad students are denoted with a year one less than the current senior class. For example, a grad student who signed into the app during the 2021-2022 academic year has year value 2021. However, this means that their data will not match the "expected grad student year" in years later (i.e., when the grad student placeholder becomes 2022, etc).

**Comment by akelch11** [comment]
Believe bug is resolved -- as shown in image below, user has class year of 2019 and is shown as Grad Student. Code changed such that years less than the current senior year are registered as grad students 
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/62965092/177253537-767ae02e-b119-4b83-bcb2-5c0ae4e07155.png">

**Comment by akelch11** [comment]
lol another issue just realized the match shouldn't say multiple dining halls but thats another issue

**Comment by akelch11** [comment]
Should be fixed, but we should examine the edit profile page where class years are input/displayed for selection to ensure bug-free
